---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: third-app-ride
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bennxumalo-devops/introargo.git
    targetRevision: HEAD
    path: environments/stg/third-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true